/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * Modified by Minghua Shen, 2026.
 */
#pragma once

// Generated by autogen/generate_kernels.py - do not edit by hand.
//
// Declarations of the 32 v2 FAGGeneral variant launchers (dtype x layout x
// headdim x softcap; each variant TU instantiates the 8 causal x
// deterministic x dropout FAGGeneral variants) plus the dispatcher macro
// used by fag_general_dispatch_impl.hpp. The macro `return`s out of the
// enclosing void dispatcher, so exactly one variant runs per dispatch.

#include "../fag_general_dispatch.hpp"

void fag_fp16_bsnd_headdim64(const FagGeneralLaunchArgs &a);
void fag_fp16_bsnd_headdim64_softcap(const FagGeneralLaunchArgs &a);
void fag_fp16_bsnd_headdim128(const FagGeneralLaunchArgs &a);
void fag_fp16_bsnd_headdim128_softcap(const FagGeneralLaunchArgs &a);
void fag_fp16_bsnd_headdim192(const FagGeneralLaunchArgs &a);
void fag_fp16_bsnd_headdim192_softcap(const FagGeneralLaunchArgs &a);
void fag_fp16_bsnd_headdim256(const FagGeneralLaunchArgs &a);
void fag_fp16_bsnd_headdim256_softcap(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim64(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim64_softcap(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim128(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim128_softcap(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim192(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim192_softcap(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim256(const FagGeneralLaunchArgs &a);
void fag_fp16_tnd_headdim256_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim64(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim64_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim128(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim128_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim192(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim192_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim256(const FagGeneralLaunchArgs &a);
void fag_bf16_bsnd_headdim256_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim64(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim64_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim128(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim128_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim192(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim192_softcap(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim256(const FagGeneralLaunchArgs &a);
void fag_bf16_tnd_headdim256_softcap(const FagGeneralLaunchArgs &a);

#define FAG_SELECT_VARIANT_16(dt, ly)                                  \
    do {                                                              \
        if (a.is_softcap) {                                           \
            switch (a.qk_headdim_kernel) {                            \
                case 64:  fag_##dt##_##ly##_headdim64_softcap(a);  return; \
                case 128: fag_##dt##_##ly##_headdim128_softcap(a); return; \
                case 192: fag_##dt##_##ly##_headdim192_softcap(a); return; \
                case 256: fag_##dt##_##ly##_headdim256_softcap(a); return; \
                default: break;                                       \
            }                                                     \
        }                                                         \
        switch (a.qk_headdim_kernel) {                            \
            case 64:  fag_##dt##_##ly##_headdim64(a);  return; \
            case 128: fag_##dt##_##ly##_headdim128(a); return; \
            case 192: fag_##dt##_##ly##_headdim192(a); return; \
            case 256: fag_##dt##_##ly##_headdim256(a); return; \
            default: break;                                       \
        }                                                         \
    } while (0)
