/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * Modified by Minghua Shen, 2026.
 */
#pragma once

// Generated by autogen/generate_kernels.py - do not edit by hand.
//
// Declarations of the 32 v2 forward combo launchers (dtype x layout x
// softcap x return_softmax x dropout; each combo TU instantiates the 6
// paged x mask FAInfer variants) plus the dispatcher macro used by
// fwd_dispatch_impl.hpp. The macro `return`s out of the enclosing void
// dispatcher, so exactly one combo runs per dispatch.

#include "../fwd_dispatch.hpp"

void fwd_combo_fp16_bsnd(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_dropout(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_retsoftmax_dropout(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap_dropout(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap_retsoftmax_dropout(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_dropout(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_retsoftmax_dropout(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap_dropout(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap_retsoftmax_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_retsoftmax_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap_retsoftmax_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_retsoftmax_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap_dropout(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap_retsoftmax(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap_retsoftmax_dropout(const FwdLaunchArgs &a);

#define FWD_SELECT_COMBO_8(dt, ly)                                                                          \
    do {                                                                                                      \
        if (!a.has_softcap && !a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly(a); return; }                 \
        if (!a.has_softcap && !a.return_softmax &&  a.has_dropout) { fwd_combo_##dt##_##ly##_dropout(a); return; }      \
        if (!a.has_softcap &&  a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly##_retsoftmax(a); return; }   \
        if (!a.has_softcap &&  a.return_softmax &&  a.has_dropout) { fwd_combo_##dt##_##ly##_retsoftmax_dropout(a); return; } \
        if ( a.has_softcap && !a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly##_softcap(a); return; }      \
        if ( a.has_softcap && !a.return_softmax &&  a.has_dropout) { fwd_combo_##dt##_##ly##_softcap_dropout(a); return; } \
        if ( a.has_softcap &&  a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly##_softcap_retsoftmax(a); return; } \
        fwd_combo_##dt##_##ly##_softcap_retsoftmax_dropout(a);                                                 \
    } while (0)
